app = 'dev-backend-internal-expansion'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8002
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
