server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: backend-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend-app-logs
          __path__: /usr/backend/app.log
    pipeline_stages:
      - regex:
          expression: "(?P<time>\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}) \\| (?P<level>\\S+) \\| (?P<message>.*)"
      - labels:
          level: level
