name: Fly Dev Deploy
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - dev  # Specify the branch

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if CI was successful
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly.dev.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
